[build] Add possibility to build BFB image from slave docker.

diff --git a/installer/bluefield/create_sonic_bfb b/installer/bluefield/create_sonic_bfb
--- a/installer/bluefield/create_sonic_bfb
+++ b/installer/bluefield/create_sonic_bfb
@@ -15,163 +15,116 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-
-
-
-# Note:
-# 1) If the installation reaches this point, then it is expected that the ONIE_INSTALLER_PAYLOAD is already built.
-#    ONIE_INSTALLER_PAYLOAD should contain squashfs, dockerfs and /boot directory
-# 2) Purpose of this script is to create installer vmlinuz, initramfs and finally bfb
-# 3) The ONIE_INSTALLER_PAYLOAD is packed inside the installer initramfs/initrd itself
-
 set -e
 
-## Pre-conditions running this script: 
-# install.sh under the SDIR
-# install.bfb under the SDIR
-# $ONIE_INSTALLER_PAYLOAD under CDIR
-# non-onie.conf under CDIR
-
-## Result:
-# sonic_BFB under DDIR
-
-IMAGE_VER="SONIC_default"
-PLATFORM="bf2"
-verbose=0
+IMAGE_VER=
+CDIR=/sonic/
+SDIR=/sonic/installer/bluefield
+DDIR=/sonic/
+WDIR=
+CAPSULE=/lib/firmware/mellanox/boot/capsule/MmcBootCap
+TARGET_MACHINE=nvidia-bluefield
 
 usage() {
 cat << EOF
 Usage: `basename $0` [ OPTIONS ]
 OPTIONS:
--i, -install_bfb,   --install_bfb <BFB>           Installation BFB to be used as a basis for the target BFB. Default: $BFB
--s, -sonic_version  --sonic_version <IMAGE_VER>   SONiC version to be installed
--m, -machine        --machine  <PLATFORM>         Bluefield Platform String. Valid Strings: bf2, bf3 Default: bf2
--v, -verbose,       --verbose                     Run script in verbose mode. Will print out each step of execution.
--h, -help,          --help                        Display help
+-i, --install_bfb <BFB>           Installation BFB to be used as a basis for the target BFB. Default: $BFB
+-s, --sonic_version <IMAGE_VER>   SONiC version to be installed
+-v, --verbose                     Run script in verbose mode. Will print out each step of execution.
+-h, --help                        Display help
 EOF
 }
 
+validate_config() {
+    if [[ $BFB == "" ]]; then
+        if [[ $BFINSTALL_FILE == "" ]]; then
+            echo "Error! Path to reference BFB is not specified! Please set BFINSTALL_FILE variable."
+            exit 1
+        fi
 
-options=$(getopt -l "install_bfb:,sonic_version:,platform:,help,verbose" -o "i:s:p:hv" -a -- "$@")
+        BFB=/sonic/$FILES_PATH/$BFINSTALL_FILE
+        if [ ! -f $BFB ]; then
+            echo "Error! Reference BFB does not exist!"
+            exit 1
+        fi
+    fi
 
-eval set -- "$options"
+    if [ ! -n "$OUTPUT_BFB_IMAGE" ]; then
+        echo "OUTPUT_BFB_IMAGE name not defined. Exiting.."
+        exit 1
+    fi
 
-while true
-do
+    if [ ! -f "$CDIR/$ONIE_INSTALLER_PAYLOAD" ]; then
+        echo "$ONIE_INSTALLER_PAYLOAD not found. Exiting.."
+        exit 1
+    fi
+
+    mkbfb=`which mlx-mkbfb`
+    if [ ! -x "${mkbfb}" ]; then
+        echo "Error! mlx-mkbfb is required to build BFB image"
+        exit 1
+    fi
+
+    if [ ! -e $CAPSULE ]; then
+        echo "ERROR: Capsule file $CAPSULE does not exist"
+        exit 1
+    fi
+}
+
+parse_args() {
+    while [[ $@ != "" ]]; do
         case $1 in
-                -h|--help)
-                    usage
-                    exit 0
-                    ;;
-                -i|--install_bfb)
-                        shift
-                        BFB=$1
-                        ;;
-                -s|--sonic_version)
-                        shift
-                        IMAGE_VER=$1
-                        ;;
-                -p|--platform)
-                        shift
-                        PLATFORM=$1
-                        ;;
-                -v|--verbose)
-                        verbose=1
-                        set -xv
-                        ;;
-                --)
-                    shift
-                    break;;
+            -h|--help)
+                usage
+                exit 0
+                ;;
+            -i|--install_bfb)
+                shift
+                BFB=$1
+                ;;
+            -s|--sonic_version)
+                shift
+                IMAGE_VER=$1
+                ;;
+            *)
+                usage
+                exit 1
+                ;;
         esac
         shift
-done
+    done
+}
 
-if [[ $PLATFORM != bf2 && $PLATFORM != bf3 ]]; then
-   echo "Unsupported bluefield machine type: $PLATFORM"
-   exit 1
-fi
+cleanup_workdir() {
+    rm -rf $WDIR
+}
 
-# Directory which has the non-onie-conf file and the sonic payload file
-CDIR=${CDIR:-/sonic/}
-# Source Directory which has the artifacts and scripts
-SDIR=${SDIR:-/sonic/installer/$PLATFORM}
-BFB=${BFB:-$SDIR/install.bfb}
-WDIR=${WDIR:-$SDIR/workspace/bfb}
-DDIR=${DDIR:-/sonic/}
-TARGET_MACHINE=nvidia-bluefield
+create_workdir() {
+    if [[ $WDIR == "" ]]; then
+        WDIR=$(mktemp -d /sonic/bfb-wd-XXXX)
+        trap cleanup_workdir EXIT
+    else
+        rm -rf $WDIR/*
+    fi
+}
 
-# Read the Configuration
-. $CDIR/onie-image-arm64.conf
+initramfs_put_installer() {
+    mkdir -p debian
 
-if [ ! -n "$OUTPUT_BFB_IMAGE" ]; then
-    echo "OUTPUT_BFB_IMAGE name not defined. Exiting.."
-    exit 1
-fi
+    cp ${SDIR}/install.sh temp_install.sh
+    sed -i -e "s/%%IMAGE_VERSION%%/$IMAGE_VER/g" temp_install.sh
+    sed -i -e "s/%%INSTALLER_PAYLOAD%%/$ONIE_INSTALLER_PAYLOAD/g" temp_install.sh
+    sed -i -e "s/%%FILESYSTEM_DOCKERFS%%/$FILESYSTEM_DOCKERFS/g" temp_install.sh
+    sed -i -e "s/%%DOCKERFS_DIR%%/$DOCKERFS_DIR/g" temp_install.sh
+    sed -i -e "s/%%FILESYSTEM_SQUASHFS%%/$FILESYSTEM_SQUASHFS/g" temp_install.sh
+    install -m 0755 temp_install.sh ./debian/install.sh
+    rm -f temp_install.sh
 
-if [ ! -f "$CDIR/$ONIE_INSTALLER_PAYLOAD" ]; then
-    echo "$ONIE_INSTALLER_PAYLOAD not found. Exiting.."
-    exit 1
-fi
+    # Copy the INSTALLER payload
+    cp $CDIR/$ONIE_INSTALLER_PAYLOAD ./debian/
 
-sonic_BFB=$OUTPUT_BFB_IMAGE
-
-SCRIPTS_DIR=`dirname $0`
-
-echo "Work directory: $WDIR"
-
-mkbfb=`which mlx-mkbfb`
-
-if [ ! -x "${mkbfb}" ]; then
-	echo "- ERROR: mlx-mkbfb is required to build BFB image"
-	exit 1
-fi
-
-if [[ ! -n "${BFB}" || ! -e "${BFB}" ]]; then
-	echo "- ERROR: Reference BFB was not found, expected: ${BFB}"
-	exit 1
-fi
-
-mkdir -p ${WDIR}
-cd ${WDIR}
-rm -rf initramfs
-$mkbfb -x ${BFB}
-
-initramfs=`ls -1 *initramfs*`
-
-initramfs_type=`file $initramfs`
-case "${initramfs_type}" in
-	*LZMA*)
-		echo "Uncompressing initramfs: $initramfs_type"
-		mv ${initramfs} ${initramfs}.xz
-		xz -d ${initramfs}.xz
-		;;
-esac
-
-rm -rf ${WDIR}/initramfs
-
-echo "Rebuilding $initramfs"
-
-mkdir -p ${WDIR}/initramfs
-cd initramfs
-cpio -id < ../$initramfs
-
-mkdir -p debian
-
-# Replace the flags
-cp ${SDIR}/install.sh temp_install.sh
-sed -i -e "s/%%IMAGE_VERSION%%/$IMAGE_VER/g" temp_install.sh
-sed -i -e "s/%%INSTALLER_PAYLOAD%%/$ONIE_INSTALLER_PAYLOAD/g" temp_install.sh
-sed -i -e "s/%%FILESYSTEM_DOCKERFS%%/$FILESYSTEM_DOCKERFS/g" temp_install.sh
-sed -i -e "s/%%DOCKERFS_DIR%%/$DOCKERFS_DIR/g" temp_install.sh
-sed -i -e "s/%%FILESYSTEM_SQUASHFS%%/$FILESYSTEM_SQUASHFS/g" temp_install.sh
-sed -i -e "s/%%PLATFORM%%/$PLATFORM/g" temp_install.sh
-install -m 0755 temp_install.sh ./debian/install.sh
-
-# Copy the INSTALLER payload
-cp $CDIR/$ONIE_INSTALLER_PAYLOAD ./debian/
-rm -rf temp_install.sh
-
-cat > etc/init.d/install-debian << EOF
+    cat > etc/init.d/install-debian << EOF
 #!/bin/sh
 
 echo
@@ -195,21 +148,54 @@ else
         echo "========================" | tee /dev/kmsg
 fi
 EOF
-chmod 755 etc/init.d/install-debian
- 
-ln -snf ../init.d/install-debian etc/rcS.d/S99install-debian
+    chmod 755 etc/init.d/install-debian
+    ln -snf ../init.d/install-debian etc/rcS.d/S99install-debian
+}
 
-# Make initramfs
-find . | cpio -H newc -o | gzip -9 > ../$initramfs
+create_initramfs() {
+    $mkbfb -x ${BFB}
+    local initramfs_template=$PWD/dump-initramfs-v0
+    local sonic_installer_initramfs=$PWD/sonic-installer-initramfs
+    if [ ! -f $initramfs_template ]; then
+        echo "Error! BFB initramfs ('$initramfs_template') is not found!"
+        exit 1
+    fi
 
-# Make bfb
-cd ..
-CAPSULE=/lib/firmware/mellanox/boot/capsule/MmcBootCap
-if [ ! -e $CAPSULE ]; then
-	echo "ERROR: Capsule file $CAPSULE does not exist"
-	exit 1
-fi
+    local initramfs_dir=$WDIR/initramfs
+    mkdir -p $initramfs_dir
+    pushd $initramfs_dir >/dev/null
+    cpio -id < $initramfs_template
 
-$PYTHON_EX $mkbfb --initramfs $initramfs --capsule $CAPSULE ${BFB} ${DDIR}/${sonic_BFB}
+    initramfs_put_installer
 
-echo "BFB is ready: `readlink -f ${DDIR}/${sonic_BFB}`"
+    find . | cpio -H newc -o | gzip -9 > $sonic_installer_initramfs
+
+    popd >/dev/null
+
+    echo $sonic_installer_initramfs
+}
+
+create_bfb_image() {
+    local initramfs=$1
+    $mkbfb --initramfs $initramfs --capsule $CAPSULE ${BFB} ${DDIR}/${OUTPUT_BFB_IMAGE}
+    echo "BFB is ready: $(readlink -f  ${DDIR}/${OUTPUT_BFB_IMAGE})"
+}
+
+main() {
+    echo $@
+    parse_args $@
+
+    . $CDIR/onie-image-arm64.conf
+
+    validate_config
+
+    create_workdir
+    echo "Work directory: $WDIR"
+    pushd $WDIR
+    local sonic_installer_initramfs=$(create_initramfs)
+
+    create_bfb_image $sonic_installer_initramfs
+    popd
+}
+
+main $@
